
///apphelp defination 
#define APPHELP_TAG_TYPE_NULL       0x1000
#define APPHELP_TAG_TYPE_BYTE       0x2000
#define APPHELP_TAG_TYPE_WORD       0x3000
#define APPHELP_TAG_TYPE_DWORD      0x4000
#define APPHELP_TAG_TYPE_QWORD      0x5000
#define APPHELP_TAG_TYPE_STRINGREF  0x6000
#define APPHELP_TAG_TYPE_LIST       0x7000
#define APPHELP_TAG_TYPE_STRING     0x8000
#define APPHELP_TAG_TYPE_BINARY     0x9000
#define APPHELP_TAG_TYPE_MASK		0xF000

// http://msdn2.microsoft.com/en-us/library/bb432487

#define APPHELP_TAG_DATABASE                (0x0001 | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_DATABASE                (0x0001 | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_LIBRARY                 (0x0002 | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_INEXCLUDE               (0x0003 | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_SHIM                    (0x0004 | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_PATCH                   (0x0005 | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_APP                     (0x0006 | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_EXE                     (0x0007 | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_MATCHING_FILE	        (0x0008 | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_SHIM_REF                (0x0009 | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_PATCH_REF               (0x000A | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_LAYER                   (0x000B | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_FILE                    (0x000C | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_APPHELP                 (0x000D | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_LINK                    (0x000E | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_DATA                    (0x000F | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_MSI_TRANSFORM           (0x0010 | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_MSI_TRANSFORM_REF       (0x0011 | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_MSI_PACKAGE             (0x0012 | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_FLAG                    (0x0013 | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_MSI_CUSTOM_ACTION       (0x0014 | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_FLAG_REF                (0x0015 | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_ACTION                  (0x0016 | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_LOOKUP                  (0x0017 | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_STRINGTABLE             (0x0801 | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_INDEXES                 (0x0802 | APPHELP_TAG_TYPE_LIST)
#define APPHELP_TAG_INDEX                   (0x0803 | APPHELP_TAG_TYPE_LIST)

#define APPHELP_TAG_NAME                    (0x0001 | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_DESCRIPTION             (0x0002 | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_MODULE                  (0x0003 | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_API                     (0x0004 | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_VENDOR                  (0x0005 | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_APP_NAME                (0x0006 | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_COMMAND_LINE            (0x0008 | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_COMPANY_NAME            (0x0009 | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_DLLFILE                 (0x000A | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_WILDCARD_NAME           (0x000B | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_PRODUCT_NAME            (0x0010 | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_PRODUCT_VERSION         (0x0011 | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_FILE_DESCRIPTION        (0x0012 | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_FILE_VERSION            (0x0013 | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_ORIGINAL_FILENAME       (0x0014 | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_INTERNAL_NAME           (0x0015 | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_LEGAL_COPYRIGHT         (0x0016 | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_16BIT_DESCRIPTION       (0x0017 | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_APPHELP_DETAILS         (0x0018 | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_LINK_URL                (0x0019 | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_LINK_TEXT               (0x001A | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_APPHELP_TITLE           (0x001B | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_APPHELP_CONTACT         (0x001C | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_SXS_MANIFEST            (0x001D | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_DATA_STRING             (0x001E | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_MSI_TRANSFORM_FILE      (0x001F | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_16BIT_MODULE_NAME       (0x0020 | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_LAYER_DISPLAYNAME       (0x0021 | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_COMPILER_VERSION        (0x0022 | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_ACTION_TYPE             (0x0023 | APPHELP_TAG_TYPE_STRINGREF)
#define APPHELP_TAG_EXPORT_NAME             (0x0024 | APPHELP_TAG_TYPE_STRINGREF)

#define APPHELP_TAG_DATABASE_ID                 (0x0007 | APPHELP_TAG_TYPE_BINARY)

#define APPHELP_TAGID_NULL (0)
#define APPHELP_TAGID_ROOT (0)

typedef ULONG TAGID;

typedef ULONG TAGREF, INDEXID, TAG;
typedef PVOID HSDB;

typedef enum
{
    DOS_PATH,
    NT_PATH,
} PATH_TYPE;

typedef struct      
{
    HANDLE  DataBaseFileHandle;
    PVOID   MappedBase;
    ULONG   Unknown;
    ULONG   FileSize;
    BYTE    DataBaseId[0x14];

    HANDLE  SectionHandle; 
} DB, *PDB;

typedef BOOL   (WINAPI *SdbRegisterDatabaseEx_) (LPCTSTR pszDatabasePath,DWORD dwDatabaseType,PULONGLONG pTimeStamp);
typedef PDB    (WINAPI *SdbOpenDatabase_)		 (LPCWSTR pwszPath,PATH_TYPE eType);
typedef TAGID  (WINAPI *SdbFindFirstTag_)		 (PDB pdb,TAGID tiParent,TAG tTag);
typedef LPTSTR (WINAPI *SdbGetStringTagPtr_)	 (PDB pdb,TAGID tiWhich);
typedef TAGID  (WINAPI * SdbFindNextTag_)		 (PDB pdb, TAGID tiParent,TAGID tiPrev);
typedef BOOL   (WINAPI * SdbReadBinaryTag_)	 (PDB pdb,TAGID tiWhich,PBYTE pBuffer,DWORD dwBufferSize);
typedef void   (WINAPI * SdbCloseDatabase_)	 (PDB pdb);
typedef BOOL   (WINAPI * ShimFlushCache_)		 (DWORD a,DWORD b,DWORD c,DWORD d);